export default [{
  pagePath: 'pages/work-bench/work-bench',
  icon: 'icon-category',
  iconPath: '../assets/image/icon/home.png',
  selectedIconPath: '../assets/image/icon/home-active.png',
  text: '首页'
}, {
  pagePath: 'pages/customer/customer',
  icon: 'icon-cart',
  iconPath: '../assets/image/icon/customer.png',
  selectedIconPath: '../assets/image/icon/customer-active.png',
  text: '客户'
}, {
  pagePath: 'pages/statistics/statistics',
  icon: 'icon-statistics',
  iconPath: '../assets/image/icon/statistics.png',
  selectedIconPath: '../assets/image/icon/statistics-active.png',
  text: '统计'
}, {
  pagePath: 'pages/finance/finance',
  icon: 'icon-finance',
  iconPath: '../assets/image/icon/finance.png',
  selectedIconPath: '../assets/image/icon/finance-active.png',
  text: '财务'
}, {
  pagePath: 'pages/messgae/messgae',
  icon: 'icon-message',
  iconPath: '../assets/image/icon/message.png',
  selectedIconPath: '../assets/image/icon/message-active.png',
  text: '消息'
}]
